modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]] #mandatory

# The modid of the mod
modId="${mod_id}" #mandatory

# The version number of the mod
version="${mod_version}" #mandatory

# A display name for the mod
displayName="${mod_name}" #mandatory

description='''
A NeoForge addon for Create with no grand vision, no theme, no concept, no balance,
no friends, no purpose in life, no "bulk sheets".AND-
And who even reads this anyway? Here,a recipe for a glass of water.
Take the glass,
take the water,
pour it into the glass,
that's it.
'''
[[mixins]]
config="create_random_bulksheet.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.7,)"
    ordering="AFTER"
    side="BOTH"

